INSS.FIP.Web/Controllers/IpController.cs
using AutoMapper;
using INSS.FIP.Interfaces;
using INSS.FIP.Models.RequestModels;
using INSS.FIP.Web.Constants;
using INSS.FIP.Web.Extensions;
using INSS.FIP.Web.Helpers;
using INSS.FIP.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace INSS.FIP.Web.Controllers;

public class IpController : Controller
{
    private readonly ILogger<IpController> _logger;
    private readonly IMapper _mapper;
    private readonly IInsolvencyPractitionerService _insolvencyPractitionerService;
    private readonly IWebMessageService _webMessageService;

    public IpController(ILogger<IpController> logger, 
        IMapper mapper, 
        IInsolvencyPractitionerService insolvencyPractitionerService,
        IWebMessageService webMessageService)
    {
        _logger = logger;
        _mapper = mapper;
        _insolvencyPractitionerService = insolvencyPractitionerService;
        _webMessageService = webMessageService;
    }

    public SearchParametersViewModel? SessionSearchParametersViewModel
    {
        get
        {
            return HttpContext.Session.GetObject<SearchParametersViewModel>(nameof(SessionSearchParametersViewModel));
        }

        set
        {
            HttpContext.Session.SetObject(nameof(SessionSearchParametersViewModel), value);
        }
    }

    public IEnumerable<SearchResultViewModel>? SessionSearchResults
    {
        get
        {
            return HttpContext.Session.GetObject<IEnumerable<SearchResultViewModel>>(nameof(SessionSearchResults));
        }

        set
        {
            HttpContext.Session.SetObject(nameof(SessionSearchResults), value);
        }
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var specialMessageViewModel = new SpecialMessageViewModel();
        var webMessageDomainModels = await _webMessageService.GetAsync("fip");
        var webMessageDomainModel = webMessageDomainModels?.FirstOrDefault();

        if (webMessageDomainModel != null)
        {
            _mapper.Map(webMessageDomainModel, specialMessageViewModel);
        }

        return View(specialMessageViewModel);
    }

    [HttpGet("search")]
    public IActionResult Search()
    {
        SessionSearchResults = default;

        var searchParametersViewModel = new SearchParametersViewModel
        {
            Breadcrumbs = BreadcrumbHelpers.BuildBreadcrumbs()
        };

        return View(searchParametersViewModel);
    }

    [HttpPost("search")]
    [ValidateAntiForgeryToken]
    public IActionResult Search([FromForm]SearchParametersViewModel searchParametersViewModel)
    {
        searchParametersViewModel.Breadcrumbs = BreadcrumbHelpers.BuildBreadcrumbs();

        if (ModelState.IsValid)
        {
            SessionSearchParametersViewModel = searchParametersViewModel;

            return RedirectToAction("Results", new { searchParametersViewModel.PageNumber });
        }

        GetSortedErrors();

        return View(searchParametersViewModel);
    }

    [HttpGet("search-results/{pageNumber?}")]
    public async Task<IActionResult> Results(int pageNumber = 1)
    {
        var searchParametersViewModel = SessionSearchParametersViewModel ?? new SearchParametersViewModel();
        searchParametersViewModel.PageNumber = pageNumber;
        SessionSearchParametersViewModel = searchParametersViewModel;

        if (ModelState.IsValid)
        {
            var searchResults = SessionSearchResults;

            if (searchResults == null || !searchResults.Any())
            {
                var searchResultDomainModels = await _insolvencyPractitionerService.SearchAsync(_mapper.Map<FipApiSearchRequestModel>(searchParametersViewModel));

                if (searchResultDomainModels != null)
                {
                    searchResults = (from a in searchResultDomainModels
                                     select _mapper.Map<SearchResultViewModel>(a)
                                    ).ToList();
                }
            }

            if (searchResults != null && searchResults.Any())
            {
                var pagedViewModel = new PagedViewModel(
                    searchParametersViewModel.PageNumber,
                    searchParametersViewModel.PageSize,
                    searchResults.Count(),
                    "search-results");

                var searchResultsViewModel = new SearchResultsViewModel
                {
                    Breadcrumbs = BreadcrumbHelpers.BuildBreadcrumbs(true, page: pageNumber),
                    Paged = pagedViewModel,
                    SearchResults = searchResults.Skip(pagedViewModel.SkipCount).Take(pagedViewModel.PageSize),
                };

                SessionSearchResults = searchResults;

                return View("Results", searchResultsViewModel);
            }

            if (searchResults == null)
            {
                ModelState.AddModelError(string.Empty, "An error occurred in the search, please try again");
            }
            else if(!searchResults.Any())
            {
                searchParametersViewModel.ShowWarningMessage = "No matches found";
            }
        }

        SessionSearchResults = default;

        GetSortedErrors();

        return View("Search", searchParametersViewModel);
    }

    [HttpGet("insolvency-practitioner-details/{ipNumber}/{pageNumber?}")]
    public async Task<IActionResult> Details(int ipNumber, int pageNumber = 1)
    {
        var insolvencyPractitionerDomainModel = await _insolvencyPractitionerService.IpGetByIpNumberAsync(ipNumber);

        if (insolvencyPractitionerDomainModel != null)
        {
            var searchResultViewModel = _mapper.Map<InsolvencyPractitionerWithAuthBodyViewModel>(insolvencyPractitionerDomainModel);

            searchResultViewModel.Breadcrumbs = BreadcrumbHelpers.BuildBreadcrumbs(true, true, page : pageNumber);

            searchResultViewModel.PageNumber = pageNumber;

            return View(searchResultViewModel);
        }

        return NotFound();
    }

    private void GetSortedErrors()
    {
        if (ModelState.ErrorCount > 0)
        {
            ViewBag.SortedErrors = ModelState
                .Select(m => new
                {
                    Key = m.Key,
                    Order = ValidationOrder.SearchFieldValidationOrder.IndexOf(m.Key),
                    Error = m.Value
                })
                .SelectMany(m => m.Error.Errors.Select(e => new
                {
                    m.Key,
                    m.Order,
                    e.ErrorMessage
                }))
                .OrderBy(m => m.Order);
        }
    }
}

INSS.FIP.Web/Views/IP/Details.cshtml
@model INSS.FIP.Web.ViewModels.InsolvencyPractitionerWithAuthBodyViewModel

@{
    ViewData["Title"] = "Insolvency practitioner details";
}

@section Breadcrumb {
    <partial name="_Breadcrumb" for=Breadcrumbs />
}

<h1 class="govuk-heading-l">@ViewData["Title"]</h1>

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <dl class="govuk-summary-list">
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    @Html.DisplayNameFor(model => model.InsolvencyPractitioner.Name)
                </dt>
                <dd class="govuk-summary-list__value">
                    @Html.DisplayFor(model => model.InsolvencyPractitioner.Name)
                </dd>
            </div>
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    @Html.DisplayNameFor(model => model.InsolvencyPractitioner.Company)
                </dt>
                <dd class="govuk-summary-list__value">
                    @Html.DisplayFor(model => model.InsolvencyPractitioner.Company)
                </dd>
            </div>
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    @Html.DisplayNameFor(model => model.InsolvencyPractitioner.Address)
                </dt>
                <dd class="govuk-summary-list__value">
                    @Html.DisplayFor(model => model.InsolvencyPractitioner.Address)
                </dd>
            </div>
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    @Html.DisplayNameFor(model => model.InsolvencyPractitioner.Telephone)
                </dt>
                <dd class="govuk-summary-list__value">
                    @Html.DisplayFor(model => model.InsolvencyPractitioner.Telephone)
                </dd>
            </div>
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    @Html.DisplayNameFor(model => model.InsolvencyPractitioner.Fax)
                </dt>
                <dd class="govuk-summary-list__value">
                    @{
                        var fax = !string.IsNullOrWhiteSpace(Model.InsolvencyPractitioner.Fax) ? Model.InsolvencyPractitioner.Fax : "N/A";
                    }
                    @fax
                </dd>
            </div>
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    @Html.DisplayNameFor(model => model.InsolvencyPractitioner.Email)
                </dt>
                <dd class="govuk-summary-list__value">
                    <a class="govuk-link" href="mailto:@Html.DisplayFor(model => model.InsolvencyPractitioner.Email)">@Html.DisplayFor(model => model.InsolvencyPractitioner.Email)</a>
                </dd>
            </div>
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    @Html.DisplayNameFor(model => model.InsolvencyPractitioner.IpNumber)
                </dt>
                <dd class="govuk-summary-list__value">
                    @Html.DisplayFor(model => model.InsolvencyPractitioner.IpNumber)
                </dd>
            </div>
        </dl>
        
        <h2 class="govuk-heading-m">Authorising body</h2>
        
        <dl class="govuk-summary-list">
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    Name
                </dt>
                <dd class="govuk-summary-list__value">@Model.AuthBody.Name</dd>
            </div>
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    Website
                </dt>
                <dd class="govuk-summary-list__value">
                    <p class="govuk-body">
                        <a href="@Model.AuthBody.Website">@Model.AuthBody.Website</a>
                    </p>
                </dd>
            </div>
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    Address
                </dt>
                <dd class="govuk-summary-list__value">
                    @if (!string.IsNullOrWhiteSpace(Model.AuthBody.AuthBodyAddressLine1))
                    {
                        @Model.AuthBody.AuthBodyAddressLine1 <br />
                    }

                    @if (!string.IsNullOrWhiteSpace(Model.AuthBody.AuthBodyAddressLine2))
                    {
                        @Model.AuthBody.AuthBodyAddressLine2 <br />
                    }
                    
                    @if (!string.IsNullOrWhiteSpace(Model.AuthBody.AuthBodyAddressLine3))
                    {
                        @Model.AuthBody.AuthBodyAddressLine3 <br />
                    }
                    
                    @if (!string.IsNullOrWhiteSpace(Model.AuthBody.AuthBodyAddressLine4))
                    {
                        @Model.AuthBody.AuthBodyAddressLine4 <br />
                    }
                    
                    @if (!string.IsNullOrWhiteSpace(Model.AuthBody.AuthBodyAddressLine5))
                    {
                        @Model.AuthBody.AuthBodyAddressLine5 <br />
                    }

                    @Model.AuthBody.AuthBodyPostcode
                </dd>
            </div>
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    Telephone number
                </dt>
                <dd class="govuk-summary-list__value">
                    <p class="govuk-body">@Model.AuthBody.Telephone</p>
                </dd>
            </div>
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    Fax number
                </dt>
                <dd class="govuk-summary-list__value">
                    <p class="govuk-body">@Model.AuthBody.Fax</p>
                </dd>
            </div>
        </dl>
        
        <a class="govuk-button" style="text-decoration:none;" asp-controller="Ip" asp-action="Search">
            Find another insolvency practitioner
        </a>
    </div>

    <div class="govuk-grid-column-one-third">

        <aside class="app-related-items" role="complementary">
            <h2 class="govuk-heading-s" id="subsection-title">
                Related content
            </h2>
            <nav role="navigation" aria-labelledby="subsection-title">
                <ul class="govuk-list govuk-!-font-size-16">
                    <li>
                        <a class="govuk-link--no-visited-state" href="https://www.gov.uk/get-help-insolvency-service">
                            Get help from the Insolvency Service
                        </a>
                    </li>
                    <li>
                        <a class="govuk-link--no-visited-state" href="https://www.gov.uk/browse/tax/court-claims-debt-bankruptcy">
                            Find out more about bankruptcy and insolvency
                        </a>
                    </li>
                </ul>
            </nav>
        </aside>

    </div>
</div>

INSS.FIP.Web/Views/IP/Index.cshtml
@model INSS.FIP.Web.ViewModels.SpecialMessageViewModel

@{
    ViewData["Title"] = "Find an insolvency practitioner";
}


@if (Model.ShowMessage)
{
    <div class="govuk-warning-text">
        <h2 class="govuk-heading-m">Special Notice</h2>
        <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
        <strong class="govuk-warning-text__text">
            <span class="govuk-warning-text__assistive">Special Notice</span>
            @Model.Message
        </strong>
    </div>

    <hr class="govuk-section-break govuk-section-break--l govuk-section-break govuk-section-break--visible">
}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-l">
            @ViewData["Title"]
        </h1>
    </div>
    <div class="govuk-grid-column-one-third">
    </div>
</div>

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">

        <p class="govuk-body">
            Find licenced insolvency practitioners in your area, including their contact details and authorising body.
            You can search by:
        </p>
        <ul class="govuk-list govuk-list--bullet">
            <li>name</li>
            <li>company</li>
            <!--
            <li>insolvency practitioner number</li>
            -->
            <li>town or city</li>
            <li>postcode</li>
        </ul>

        @if (!Model.HideSearch)
        {
            <a asp-controller="IP" asp-action="Search" role="button" draggable="false" class="govuk-button govuk-button--start" data-module="govuk-button">
                Start now
                <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" aria-hidden="true" focusable="false">
                    <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z" />
                </svg>
            </a>

        }

        <h2 class="govuk-heading-m">Before you start</h2>

        <p class="govuk-body">
            The service contains information about insolvency practitioners who have agreed to include their details.
            It is <strong>not</strong> a complete list of all insolvency practitioners in the UK.
        </p>


    </div>

    <div class="govuk-grid-column-one-third">

        <aside class="app-related-items" role="complementary">
            <h2 class="govuk-heading-s" id="subsection-title">
                Related content
            </h2>
            <nav role="navigation" aria-labelledby="subsection-title">
                <ul class="govuk-list govuk-!-font-size-16">
                    <li>
                        <a class="govuk-link--no-visited-state" href="https://www.gov.uk/get-help-insolvency-service">
                            Get help from the Insolvency Service
                        </a>
                    </li>
                    <li>
                        <a class="govuk-link--no-visited-state" href="https://www.gov.uk/browse/tax/court-claims-debt-bankruptcy">
                            Find out more about bankruptcy and insolvency
                        </a>
                    </li>
                </ul>
            </nav>
        </aside>

    </div>
</div>

INSS.FIP.Web/Views/IP/Results.cshtml
@model INSS.FIP.Web.ViewModels.SearchResultsViewModel

@{
    ViewData["Title"] = "Search results";
}

@section Breadcrumb {
    <partial name="_Breadcrumb" for=Breadcrumbs />
}

@if(Model?.SearchResults != null && Model.SearchResults.Any())
{
    <div class="govuk-grid-row">
            <h1 class="govuk-heading-l">
                @ViewData["Title"]
            </h1>
        <p class="govuk-body">Select the name of an insolvency practitioner to view their details.</p>
    </div>

    <div class="govuk-grid-row">
        <form asp-controller="IP" asp-action="Results">
            <table class="govuk-table">
                <thead class="govuk-table__head">
                    <tr class="govuk-table__row">
                        <th scope="col" class="govuk-table__header govuk-!-width-one-third">@Html.DisplayNameFor(model => model.SearchResults!.First().Name)</th>
                        <th scope="col" class="govuk-table__header govuk-!-width-one-third">@Html.DisplayNameFor(model => model.SearchResults!.First().Company)</th>
                        <th scope="col" class="govuk-table__header">@Html.DisplayNameFor(model => model.SearchResults!.First().Town)</th>
                        <th scope="col" class="govuk-table__header">@Html.DisplayNameFor(model => model.SearchResults!.First().Postcode)</th>
                    </tr>
                </thead>
                <tbody class="govuk-table__body">
                    @foreach (var searchResult in Model.SearchResults) {
                        <tr class="govuk-table__row">
                            <td class="govuk-table__cell">
                                <a class="govuk-link govuk-link--no-visited-state" asp-controller="IP", asp-action="Details"
                                   asp-route-ipNumber="@searchResult.IpNumber" asp-route-pageNumber="@Model.Paged.PageNumber">@Html.DisplayFor(modelItem => searchResult.Name)</a>
                            </td>
                            <td class="govuk-table__cell">@Html.DisplayFor(modelItem => searchResult.Company)</td>
                            <td class="govuk-table__cell">@Html.DisplayFor(modelItem => searchResult.Town)</td>
                            <td class="govuk-table__cell">@Html.DisplayFor(modelItem => searchResult.Postcode)</td>
                        </tr>
                    }
                </tbody>
                <ftoot>
                    <tr class="govuk-table__row">
                        <td class="govuk-table__cell" colspan="6">
                            @if (Model?.Paged?.TotalResults > Model?.SearchResults.Count())
                            {
                               <partial name="_Paging" for=Paged />
                            }
                        </td>
                    </tr>
                </ftoot>
            </table>
        </form>
    </div>
}

INSS.FIP.Web/Views/IP/Search.cshtml
@model INSS.FIP.Web.ViewModels.SearchParametersViewModel
@{
    ViewData["Title"] = "Search";

    var firstNameError = ViewContext?.ModelState["FirstName"]?.Errors != null && ViewContext.ModelState["FirstName"].Errors.Count > 0;
    var lastNameError = ViewContext?.ModelState["LastName"]?.Errors != null && ViewContext.ModelState["LastName"].Errors.Count > 0;
    var companyError = ViewContext?.ModelState["Company"]?.Errors != null && ViewContext.ModelState["Company"].Errors.Count > 0;
    var townError = ViewContext?.ModelState["Town"]?.Errors != null && ViewContext.ModelState["Town"].Errors.Count > 0;
    var postcodeError = ViewContext?.ModelState["Postcode"]?.Errors != null && ViewContext.ModelState["Postcode"].Errors.Count > 0;
}

@section Breadcrumb 
{
    <partial name="_Breadcrumb" for=Breadcrumbs />
}

@{
    if (!string.IsNullOrWhiteSpace(Model.ShowWarningMessage))
    {
        <div class="govuk-warning-text">
            <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
            <strong class="govuk-warning-text__text">
            <span class="govuk-warning-text__assistive">Warning</span>
                @Model.ShowWarningMessage
            </strong>
        </div>
    }
}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        
        @await Html.PartialAsync("_ValidationSummary", ViewData.ModelState)

        <h1 class="govuk-heading-l">Search</h1>

        <p class="govuk-body govuk-input--width-30">You can search for an insolvency practitioner by name, company, town, city or postcode.</p>

        <form asp-controller="IP" asp-action="Search" method="post" class="inss-app-validation">
            @Html.AntiForgeryToken()
            
            <input type="hidden" asp-for="PageNumber" />
            <input type="hidden" asp-for="PageSize" />
            
            <div class="@(firstNameError ? "govuk-form-group govuk-form-group--error" : "govuk-form-group")">
                <label class="govuk-label" for="FirstName">
                    First name
                </label>
                @if (firstNameError)
                {
                    @await Html.PartialAsync("_ValidationError", ViewContext.ModelState["FirstName"].Errors)
                }
                <input class="govuk-input govuk-input--width-30" id="FirstName" name="FirstName" type="text" asp-for="FirstName">
            </div>

            <div class="@(lastNameError ? "govuk-form-group govuk-form-group--error" : "govuk-form-group")">
                <label class="govuk-label" for="LastName">
                    Last name
                </label>
                @if (lastNameError)
                {
                    @await Html.PartialAsync("_ValidationError", ViewContext.ModelState["LastName"].Errors)
                }
                <input class="govuk-input govuk-input--width-30" id="LastName" name="LastName" type="text" asp-for="LastName">
            </div>

            <div class="@(companyError ? "govuk-form-group govuk-form-group--error" : "govuk-form-group")">
                <label class="govuk-label" for="Company">
                    Company
                </label>
                @if (companyError)
                {
                    @await Html.PartialAsync("_ValidationError", ViewContext.ModelState["Company"].Errors)
                }
                <input class="govuk-input govuk-input--width-30" id="Company" name="Company" type="text" asp-for="Company">
            </div>

            <div class="@(townError ? "govuk-form-group govuk-form-group--error" : "govuk-form-group")">
                <label class="govuk-label" for="Town">
                    Town or city
                </label>
                @if (townError)
                {
                    @await Html.PartialAsync("_ValidationError", ViewContext.ModelState["Town"].Errors)
                }
                <input class="govuk-input govuk-input--width-30" id="Town" name="Town" type="text" asp-for="Town">
            </div>

            <div class="@(postcodeError ? "govuk-form-group govuk-form-group--error" : "govuk-form-group")">
                <label class="govuk-label" for="Postcode">
                    Postcode
                </label>
                @if (postcodeError)
                {
                    @await Html.PartialAsync("_ValidationError", ViewContext.ModelState["Postcode"].Errors)
                }
                <input class="govuk-input govuk-input--width-10" id="Postcode" name="Postcode" type="text" asp-for="Postcode">
            </div>

            <button data-prevent-double-click="true" class="govuk-button" data-module="govuk-button" type="submit">
                Search
            </button>
        </form>
    </div>
    
    <div class="govuk-grid-column-one-third">
        <aside class="app-related-items" role="complementary">
            <h2 class="govuk-heading-s" id="subsection-title">
                Related content
            </h2>
            <nav role="navigation" aria-labelledby="subsection-title">
                <ul class="govuk-list govuk-!-font-size-16">
                    <li>
                        <a class="govuk-link--no-visited-state" href="https://www.gov.uk/get-help-insolvency-service">
                            Get help from the Insolvency Service
                        </a>
                    </li>
                    <li>
                        <a class="govuk-link--no-visited-state" href="https://www.gov.uk/browse/tax/court-claims-debt-bankruptcy">
                            Find out more about bankruptcy and insolvency
                        </a>
                    </li>
                </ul>
            </nav>
        </aside>
    </div>
</div>